In [1]:
import pandas as pd

file_id = "1fVkeUdzuBjqHsLPtL_AzUOeL4kX4Y7sV"  # ID файла на Google Drive
file_url = f"https://drive.google.com/uc?id={file_id}"

raw_data = pd.read_csv(file_url)  # читаем файл

raw_data.head(10)

,Patient_ID,Age,Gender,BMI,Smoking_Status,Alcohol_Consumption,Physical_Activity_Level,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Cholesterol_Level,Glucose_Level,Family_History,Genetic_Risk_Score,Previous_Diagnosis,Disease_Risk
0,P100000,69,Female,27.8,Never,NaN,Low,92,117,297,156,Yes,0.52,NaN,No
1,P100001,32,Female,32.0,Never,Moderate,Moderate,149,77,279,163,Yes,0.50,NaN,Yes
2,P100002,89,Male,24.2,Former,High,High,124,82,189,139,Yes,0.37,Diagnosed,No
3,P100003,78,Male,23.8,Never,NaN,Moderate,118,81,159,169,No,0.55,NaN,No
4,P100004,38,Male,29.8,Never,Moderate,Moderate,164,63,213,97,Yes,0.59,Pre-disease,No
5,P100005,41,Male,27.0,Never,NaN,Low,159,107,191,155,Yes,0.54,NaN,No
6,P100006,20,Female,26.7,Former,NaN,Moderate,172,70,242,187,No,0.35,NaN,No
7,P100007,39,Female,34.8,Never,NaN,Moderate,134,77,189,80,No,0.38,Pre-disease,No
8,P100008,70,Male,30.0,Never,High,Moderate,116,114,293,198,No,0.43,Diagnosed,No
9,P100009,19,Female,17.1,Never,Moderate,Low,158,107,274,138,No,0.63,NaN,No

In [2]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient_ID                4000 non-null   object
 1   Age                       4000 non-null   int64
 2   Gender                    4000 non-null   object
 3   BMI                       4000 non-null   float64
 4   Smoking_Status            4000 non-null   object
 5   Alcohol_Consumption       2361 non-null   object
 6   Physical_Activity_Level   4000 non-null   object
 7   Blood_Pressure_Systolic   4000 non-null   int64
 8   Blood_Pressure_Diastolic  4000 non-null   int64
 9   Cholesterol_Level         4000 non-null   int64
 10  Glucose_Level             4000 non-null   int64
 11  Family_History            4000 non-null   object
 12  Genetic_Risk_Score        4000 non-null   float64
 13  Previous_Diagnosis        1973 non-null   object
 14  Disease_Risk              4000 non-null   object
dtypes: float64(2), int64(5), object(8)
memory usage: 468.9+ KB